"""
ASGI entrypoint for serving DualCellQuant behind a reverse proxy at a subpath.

Key points for subpath (e.g. /dualcellquant):
- Configure FastAPI(root_path="/dualcellquant") so URLs are generated with the prefix.
- Trust proxy headers so that scheme/host are preserved when Apache passes X-Forwarded-*.
- Mount Gradio at "/" inside the app; the external path prefix is provided by root_path.

If you need a different prefix, set environment variable ROOT_PATH accordingly.
"""

import os
from fastapi import FastAPI
import gradio as gr

from dualCellQuant import build_ui  # 既存の build_ui() を利用


# Allow overriding from environment, default to the deployed subpath
ROOT_PATH = os.getenv("ROOT_PATH", "/dualcellquant")

# FastAPI app configured with root_path so URL generation respects the subpath
app = FastAPI(root_path=ROOT_PATH)

# Build Gradio UI and mount at "/"; external path becomes {ROOT_PATH}/
demo = build_ui().queue()
app = gr.mount_gradio_app(app, demo, path="/")


class ForwardedHeadersMiddleware:
	"""Minimal ASGI middleware to respect reverse-proxy headers.

	- Applies ROOT_PATH or X-Forwarded-Prefix to scope['root_path']
	- Applies X-Forwarded-Proto to scope['scheme']
	- Applies X-Forwarded-Host to scope['server']
	"""

	def __init__(self, app, default_root_path: str | None = None):
		self.app = app
		self.default_root_path = (default_root_path or "").rstrip("/") or None

	async def __call__(self, scope, receive, send):
		if scope.get("type") in ("http", "websocket"):
			try:
				headers = {k.decode().lower(): v.decode() for k, v in (scope.get("headers") or [])}
			except Exception:
				headers = {}

			# root_path from header or default
			root = headers.get("x-forwarded-prefix") or self.default_root_path
			if root:
				scope["root_path"] = root.rstrip("/")

			# scheme
			proto = headers.get("x-forwarded-proto")
			if proto:
				scope["scheme"] = proto

			# host (may include port)
			xf_host = headers.get("x-forwarded-host")
			if xf_host:
				host, _, port = xf_host.partition(":")
				try:
					port_i = int(port) if port else (443 if scope.get("scheme") == "https" else 80)
				except Exception:
					port_i = 443 if scope.get("scheme") == "https" else 80
				scope["server"] = (host, port_i)

		await self.app(scope, receive, send)


# Wrap the app so URLs generated by Gradio/FastAPI honor proxy headers
app = ForwardedHeadersMiddleware(app, default_root_path=ROOT_PATH)
